import { Check, Megaphone, Target, Zap } from "lucide-react";

const services = [
  { icon: Target, title: "Développement", description: "Des sites web et logiciels sur mesure, axés sur la performance, l’évolutivité et des résultats concrets pour votre activité.", features: ["Développement web et SaaS moderne", "API et architecture backend", "Optimisation des performances"] },
  { icon: Zap, title: "Génération de prospects", description: "Des stratégies fondées sur les données pour attirer, qualifier et convertir des prospects à fort potentiel.", features: ["Pages d’atterrissage et tunnels", "Publicité payante", "CRM et automatisation des prospects"] },
  { icon: Megaphone, title: "Publicité créative", description: "Des campagnes qui captent l’attention et fidélisent les bonnes audiences.", features: ["Direction artistique", "Campagnes sur les réseaux sociaux", "Positionnement de marque"] },
];

export function Services() {
  return <section id="services" className="relative z-1 mx-auto w-[min(100%-2.5rem,1180px)] py-12 text-center sm:py-20"><p className="inline-flex items-center gap-2 rounded-full border border-[#65891c]/50 bg-[#65891c]/15 px-3.5 py-2 font-mono text-[11px] uppercase tracking-[.2em] text-[#bafc0c]"><span className="size-1.5 rounded-full bg-[#bafc0c]" />Nos services</p><h2 className="mt-5 text-balance text-[clamp(2rem,5vw,4rem)] font-black leading-none tracking-[-.045em]">Nous vous accompagnons <em className="text-[#bafc0c]">dans les domaines suivants</em></h2><p className="mx-auto mt-5 max-w-2xl text-base leading-relaxed text-[#b6b9bb] sm:text-lg">Des solutions complètes pour faire grandir votre activité durablement.</p><div className="mt-12 grid gap-5 text-left md:grid-cols-3">{services.map(({ icon: Icon, title, description, features }) => <article className="group rounded-2xl border border-white/10 bg-white/[0.03] p-6 transition duration-300 hover:-translate-y-2 hover:border-[#65891c] hover:shadow-[0_0_30px_rgba(186,252,12,0.2)]" key={title}><div className="mb-6 grid size-14 place-items-center rounded-xl bg-[#65891c]"><Icon size={29} aria-hidden="true" /></div><h3 className="text-xl font-black tracking-[-.045em]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#b6b9bb]">{description}</p><ul className="mt-6 grid gap-3 text-sm text-gray-300">{features.map((feature) => <li className="flex items-center gap-2.5" key={feature}><Check className="box-content rounded-full bg-[#65891c] p-0.5" size={13} aria-hidden="true" />{feature}</li>)}</ul></article>)}</div></section>;
}
